### PR TITLE
Automated Linux installation script and delete "Windows 10 basic apps" script.

### PR DESCRIPTION
**Pull request by linux-lukas**

### CODE REVIEW

**Comment by pintman** [comment]
Das sieht schon gut aus. Bitte nur eine Funktionalität pro PR. Dann lieber zwei PRs erstellen. Einmal Linux-Install-Script und einmal Windows-Deinstall-Skript.

**Comment by linux-lukas** [comment]
I think I'm going to make a lot of "RENAME master to main PRs soon.

**Comment by linux-lukas** [comment]
Will this PR still be added to the Main Branch, or should I create a single one each, @pintman ?

**Comment by pintman** [comment]
Better create one PR for each feature to be added.

**Comment by linux-lukas** [comment]
All right, then I'll probably create three or four separate pull requests, because I've found more ideas for possibly useful scripts and other cool free and open source software.

**Pull request closed without merging**
